<?php

use App\Http\Controllers\AboutController;
use App\Http\Controllers\AllProductController;
use App\Http\Controllers\AspahltDistributorController;
use App\Http\Controllers\BulldozerController;
use App\Http\Controllers\CargoTruck14RealftController;
use App\Http\Controllers\CargoTruck20ftController;
use App\Http\Controllers\CargoTruck6WheelerController;
use App\Http\Controllers\ContactController;
use App\Http\Controllers\CookiePolicyController;
use App\Http\Controllers\DumpTruck12CubicController;
use App\Http\Controllers\DumpTruck6cbmController;
use App\Http\Controllers\ExcavatorController;
use App\Http\Controllers\ForkliftController;
use App\Http\Controllers\ForlandCargoTruck17ftController;
use App\Http\Controllers\ForlandDumpTruck3CBMController;
use App\Http\Controllers\ForlandM6Controller;
use App\Http\Controllers\ForlandT5_4x2DumpTruckController;
use App\Http\Controllers\FTRController;
use App\Http\Controllers\FVRController;
use App\Http\Controllers\GarbageTruck5CubicController;
use App\Http\Controllers\Giga4x2CargoHeadController;
use App\Http\Controllers\Giga4x2TractorHeadController;
use App\Http\Controllers\Giga6x2CargoHeadController;
use App\Http\Controllers\Giga6x4CargoHeadController;
use App\Http\Controllers\Giga6x4DumpTruckController;
use App\Http\Controllers\Giga6x4TractorHeadController;
use App\Http\Controllers\Giga8x4CargoHeadController;
use App\Http\Controllers\GigaBoomController;
use App\Http\Controllers\GigaMixerTruck10W10CBMController;
use App\Http\Controllers\GraderController;
use App\Http\Controllers\GTH6x4_300HPController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Isuzu1500LitersPtoFiretruckController;
use App\Http\Controllers\Isuzu6000LitersPtoFiretruckController;
use App\Http\Controllers\Isuzu6WGarbageController;
use App\Http\Controllers\Isuzu700PffrController;
use App\Http\Controllers\IsuzuBusController;
use App\Http\Controllers\IsuzuSewageController;
use App\Http\Controllers\L3CargoTruckController;
use App\Http\Controllers\L5CargoTruckController;
use App\Http\Controllers\L7CargoTruckController;
use App\Http\Controllers\MixerTruck4CubicController;
use App\Http\Controllers\MixerTruck6CubicController;
use App\Http\Controllers\NKR600PController;
use App\Http\Controllers\NPR700PController;
use App\Http\Controllers\OilFuelWaterTanker10CubicController;
use App\Http\Controllers\OilFuelWaterTanker4CubicController;
use App\Http\Controllers\Powergen182750KVAController;
use App\Http\Controllers\Powerquip155850KVAController;
use App\Http\Controllers\PrivacyPolicyController;
use App\Http\Controllers\RoadRollerController;
use App\Http\Controllers\ShacmanDumpTruckH3000Controller;
use App\Http\Controllers\ShacmanDumpTruckX3000Controller;
use App\Http\Controllers\ShacmanEvController;
use App\Http\Controllers\ShacmanFuelTankerController;
use App\Http\Controllers\ShacmanMixerController;
use App\Http\Controllers\ShacmanSelfLoaderController;
use App\Http\Controllers\ShacmanTractorheadH3000Controller;
use App\Http\Controllers\ShacmanTractorheadx3000Controller;
use App\Http\Controllers\ShacmanWingVanController;
use App\Http\Controllers\Sinotruk4CubicMeterDumpTruckController;
use App\Http\Controllers\Sinotruk4x2ManliftTruckController;
use App\Http\Controllers\T3CargoTruckController;
use App\Http\Controllers\T5CargoTruckController;
use App\Http\Controllers\T5ModernJeepneyClass1Controller;
use App\Http\Controllers\TermsOfUseController;
use App\Http\Controllers\WheelLoaderController;
use Illuminate\Support\Facades\Route;

Route::resource('/', HomeController::class);
Route::resource('/products', AllProductController::class);
Route::resource('/about', AboutController::class);
Route::resource('/contact', ContactController::class);
Route::resource('/privacy-and-policy', PrivacyPolicyController::class);
Route::resource('/terms-of-use', TermsOfUseController::class);
Route::resource('/cookie-policy', CookiePolicyController::class);

// Weichai
Route::resource('/excavator', ExcavatorController::class);
Route::resource('/road-roller', RoadRollerController::class);
Route::resource('/forklift', ForkliftController::class);
Route::resource('/grader', GraderController::class);
Route::resource('/wheel-loader', WheelLoaderController::class);
Route::resource('/bulldozer', BulldozerController::class);

// Powerquip
Route::resource('/powerquip-15-5850-kva', Powerquip155850KVAController::class);

// Powergen
Route::resource('/powergen-18-2750-kva', Powergen182750KVAController::class);

// Shacman
Route::resource('/shacman-tractorhead-x3000', ShacmanTractorheadx3000Controller::class);
Route::resource('/shacman-tractorhead-h3000', ShacmanTractorheadH3000Controller::class);
Route::resource('/shacman-mixer', ShacmanMixerController::class);
Route::resource('/ev-shacman', ShacmanEvController::class);
Route::resource('/shacman-fuel-tanker', ShacmanFuelTankerController::class);
Route::resource('/shacman-self-loader', ShacmanSelfLoaderController::class);
Route::resource('/shacman-wing-van', ShacmanWingVanController::class);
Route::resource('/shacman-dump-truck-h3000', ShacmanDumpTruckH3000Controller::class);
Route::resource('/shacman-dump-truck-x3000', ShacmanDumpTruckX3000Controller::class);

// Sinotruk
Route::resource('/cargo-truck-6-wheeler', CargoTruck6WheelerController::class);
Route::resource('/four-cubic-meter-dump-truck', Sinotruk4CubicMeterDumpTruckController::class);
Route::resource('/dump-truck-12-cubic', DumpTruck12CubicController::class);
Route::resource('/garbage-truck-5-cubic', GarbageTruck5CubicController::class);
Route::resource('/sinotruk-4x2-manlift-truck', Sinotruk4x2ManliftTruckController::class);
Route::resource('/mixer-truck-4-cubic', MixerTruck4CubicController::class);
Route::resource('/mixer-truck-6-cubic', MixerTruck6CubicController::class);
Route::resource('/oil-fuel-tanker-4-cubic', OilFuelWaterTanker4CubicController::class);
Route::resource('/oil-fuel-tanker-10-cubic', OilFuelWaterTanker10CubicController::class);

// Forland
Route::resource('/cargo-truck-14-realft', CargoTruck14RealftController::class);
Route::resource('/cargo-truck-20ft', CargoTruck20ftController::class);
Route::resource('/dump-truck-6cbm', DumpTruck6cbmController::class);
Route::resource('/l7-cargo-truck', L7CargoTruckController::class);
Route::resource('/l3-cargo-truck', L3CargoTruckController::class);
Route::resource('/l5-cargo-truck', L5CargoTruckController::class);
Route::resource('/forland-m6', ForlandM6Controller::class);
Route::resource('/t3-cargo-truck', T3CargoTruckController::class);
Route::resource('/t5-cargo-truck', T5CargoTruckController::class);
Route::resource('/t5-modern-jeepney-class-1', T5ModernJeepneyClass1Controller::class);
Route::resource('/forland-t5-4x2-dump-truck', ForlandT5_4x2DumpTruckController::class);
Route::resource('/forland-cargo-truck-17ft', ForlandCargoTruck17ftController::class);
Route::resource('/forland-dump-truck-3CBM', ForlandDumpTruck3CBMController::class);

// Kingling Isuzu
Route::resource('/isuzu-700-pffr', Isuzu700PffrController::class);
Route::resource('/aspahlt-distributor', AspahltDistributorController::class);
Route::resource('/dump-truck-6cbm', DumpTruck6cbmController::class);
Route::resource('/ftr', FTRController::class);
Route::resource('/fvr', FVRController::class);
Route::resource('/giga-4x2-cargo-head', Giga4x2CargoHeadController::class);
Route::resource('/giga-4x2-tractor-head', Giga4x2TractorHeadController::class);
Route::resource('/giga-6x2-cargo-head', Giga6x2CargoHeadController::class);
Route::resource('/giga-6x4-cargo-head', Giga6x4CargoHeadController::class);
Route::resource('/giga-6x4-dump-truck', Giga6x4DumpTruckController::class);
Route::resource('/giga-6x4-tractor-head', Giga6x4TractorHeadController::class);
Route::resource('/giga-8x4-cargo-head', Giga8x4CargoHeadController::class);
Route::resource('/giga-boom', GigaBoomController::class);
Route::resource('/giga-mixer-truck-10W-10CBM', GigaMixerTruck10W10CBMController::class);
Route::resource('/gth-6x4-300HP', GTH6x4_300HPController::class);
Route::resource('/isuzu-6w-garbage', Isuzu6WGarbageController::class);
Route::resource('/isuzu-bus', IsuzuBusController::class);
Route::resource('/FVR-6-Wheeler-Firetruck', Isuzu6000LitersPtoFiretruckController::class);
Route::resource('/NLR-4-Wheeler-Firetruck', Isuzu1500LitersPtoFiretruckController::class);
Route::resource('/kingling-isuzu-sewage', IsuzuSewageController::class);
Route::resource('/nkr-600p', NKR600PController::class);
Route::resource('/npr-700p', NPR700PController::class);